---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "python dependencies"
      - "triage"
    reviewers:
      - "your-github-username"
    assignees:
      - "your-github-username"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "github actions"
      - "triage"
    reviewers:
      - "your-github-username"
    assignees:
      - "your-github-username"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
