---
- name: Host inspector base inspection
  host_inspector:
    verbosity: "{{ verbosity }}"
    action: base-inspection
  register: results

- name: Debug base inspection
  ansible.builtin.debug:
    var: results
