---
# tasks file for brainxio.host_inspector

- name: Perform preparations
  block:
    - name: Ensuring directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: "0755"
      loop:
        - "{{ logging_path }}"
        - "{{ data_path }}"
      delegate_to: localhost
      run_once: true

- name: Basic host inspection
  block:
    - name: Include default inspection
      ansible.builtin.include_tasks: default_inspection.yml
