---
# tasks file for BrainXio.host_inspector

- name: Perform Preparations
  block:
    - name: Ensure directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: "0755"
      loop:
        - "{{ logging_path }}"
        - "{{ data_path }}"
      delegate_to: localhost
      run_once: true

- name: Host Inspection
  block:
    - name: Include tasks host inspector
      ansible.builtin.include_tasks: host_inspector.yml
